### ISSUE TITLE
Problème d'exécution dans Terminal sous macOS

### ISSUE THREAD

**Issue by iFredOS** [phyver/GameShell#1]
Est-ce possible de faire fonctionner ce jeu sous macOS? Voici ce que ça me fait quand je tente d'exécuter "./start.sh"

```
> ============================ Initialisation de GameShell ============================
> ./start.sh: line 110: /.session_data/passeport.txt: No such file or directory
> ./start.sh: line 234: sha1sum: command not found
> ./start.sh: line 235: /.session_data/passeport.txt: No such file or directory
> ./start.sh: line 236: /.session_data/uid: No such file or directory
> ./start.sh: line 243: cd: /World: No such file or directory
> cat: /.session_data/uid: No such file or directory
```

**Comment by rlepigre** [comment]
Il y a visiblement deux problèmes. D'abord, la commande `sha1sum` ne semble pas exister sur votre système, il faut donc l'installer. D'après [cette réponse](https://stackoverflow.com/questions/28490500/how-to-installing-sha1sum-in-mac-os), et si vous utilisez `homebrew` il suffit d'entrer la commande `brew install md5sha1sum`.

Le second problème est plus étrange, car le chemin `/.session_data/passeport.txt` ne me semble pas correct (en particulier le slash au début). Pouvez vous nous donner la résultat des trois commandes suivantes (en supposant que vous êtres dans le dossier `GameShell`)?
```bash
dirname ./start.sh
readlink -f .
readlink -f "$(dirname ./start.sh)"
```

**Comment by phyver** [comment]
Nous n'avons pas testé GameShell sous MacOS, n'hésite pas à faire d'autre retours !

Pour ton problème, il semblerait que la command ``readlink`` n'existe pas non plus sous MacOS ([lien](https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac)) ! Pour ceci, il faut installer ``coreutils`` avec ``brew install coreutils``.

Comme la commande s'appelle alors ``greadlink``, j'ai du faire un petit patch pour l'utiliser. 

Met ton dépot à jours et dis moi si ça marche !

**Comment by iFredOS** [comment]
J'ai installé `homebrew` avec avec `md5sha1sum` et `coreutils`, mais ça ne démarre toujours pas.

```
$ ./start.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
mkdir: /World: Permission denied
mkdir: /.session_data: Permission denied
./start.sh: line 195: /.session_data/missions.log: No such file or directory
mkdir: /.config: Permission denied
cp: /lib/bashrc: No such file or directory
mkdir: /.bin: Permission denied
mkdir: /.tmp: Permission denied

============================ Initialisation de GameShell ============================
./start.sh: line 127: /.session_data/passeport.txt: No such file or directory
sha1sum: stat '/.session_data/passeport.txt': No such file or directory
./start.sh: line 258: /.session_data/passeport.txt: No such file or directory
./start.sh: line 259: /.session_data/uid: No such file or directory
./start.sh: line 266: cd: /World: No such file or directory
cat: /.session_data/uid: No such file or directory

```

Vous pouvez rajouter à votre README comment installer « homebrew », en entrant la commande suivante :

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

**Comment by phyver** [comment]
Zut, j'avais pas réalisé que MacOS avait quand même une commande ``readlink`` : mon test ne fonctionnait pas.
Est-ce que c'est mieux maintenant ?

**Comment by iFredOS** [comment]
Ça démarre maintenant sans erreurs. Merci beaucoup! 😄 Ça sera très pratique pour tous les étudiants à mon université (UQÀM) qui utilise macOS. Votre jeu est très utile pour apprendre.

Il va juste rester à mettre à jour le README.md

Pour l'installation du `homebrew` : 
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

et installer `brew install md5sha1sum`

**Comment by iFredOS** [comment]
> Zut, j'avais pas réalisé que MacOS avait quand même une commande `readlink` : mon test ne fonctionnait pas.
> Est-ce que c'est mieux maintenant ?

Donc pour reprendre mon message précédent. Ça démarre sans erreurs si `greadlink` est installé. Je l'ai désinstallé à cause que ce n'est plus nécessaire, mais il me donne une erreur parce qu'il n'est plus installé.

**Comment by phyver** [comment]
``greadlink`` est nécessaire car la version ``readlink`` de MacOS ne supporte pas les mêmes options que la version GNU.

Normalement, si tu n'as pas ``greadlink``, le script devrait afficher une erreur 

    La commande 'readlink' (linux) ou 'greadlink' (MacOS) ne supporte pas l'argument '-f'...
    Pour MacOS, n'oubliez pas d'installer 'coreutil' (et 'md5sha1sum')
    $ brew install coreutils
    $ brew install md5sha1sum

Est-ce que c'est bien le cas ?

**Comment by iFredOS** [comment]
Effectivement c'est le cas. Donc, je pense que c'est maintenant 100 % fonctionel. Dernier petit détail à changer par convention, « macOS » s'écrit avec un « m» minuscule. ([apple.com/macos](https://apple.com/macos/)).

Encore merci et s'il y a d'autres problèmes je ferai un autre « bug report ».
