### ISSUE TITLE
Running tests xeyes still opened

### ISSUE THREAD

**Issue by Mte90** [phyver/GameShell#103]
If I run:
```
    $ ./utils/archive.sh -a
    $ ./gameshell.sh -dc 'for _ in $(seq 42); do gsh auto --abort; done' 
```

I get the xeyes running also if the tests are finished or failed.

**Comment by phyver** [comment]
Right.
The `auto.sh` script cannot kill it, as it is necessary to validate the mission.
Since the order of missions is not fixed, I didn't want to kill it in the next mission.

I'll add something like `( sleep 1; kill xeyes )&` just before the `gsh check` in the `auto.sh` script.
