### ISSUE TITLE
mission 12

### ISSUE THREAD

**Issue by lescobales** [phyver/GameShell#107]
Lors du gsh check, il semble que le fichier tableau copié dans le coffre soit effacé.

**Comment by phyver** [comment]
C'est l'initialisation de la mission qui supprime les tableaux présents dans le coffre.
Si `gsh check` réussit, le tableau devrait donc rester dans le coffre.

Tu peux vérifier ?

**Comment by lescobales** [comment]
Je copy le tableau dans mon coffre et `gsh check` me dit que la mission a échoué et supprime le fichier.
`-rw-r--r-- 1 nicolas nicolas 1055 août   3 08:43 tableau_QtwXZYRV

~
[mission 12] $ gsh check 
Le tableau n'est pas dans votre coffre...

Désolé, la mission 12 a échoué.


  |                                            |
--+--------------------------------------------+--
  | Tapez la commande                          |
  | $ gsh help                                 |
  | pour obtenir la liste des commandes "gsh". |
--+--------------------------------------------+--
  |                                            |


~
[mission 12] $ ls -l Foret/Hutte/Coffre/
total 68
-rw-r--r-- 1 nicolas nicolas  785 août   3 08:42 12078_tapisserie_06
-rw-r--r-- 1 nicolas nicolas 1214 août   3 08:42 1500_tapisserie_07
-rw-r--r-- 1 nicolas nicolas 3877 août   3 08:42 23_tapisserie_08
-rw-r--r-- 1 nicolas nicolas 1290 août   3 08:42 40040_tapisserie_04
-rw-r--r-- 1 nicolas nicolas  574 août   3 08:42 44749_tapisserie_09
-rw-r--r-- 1 nicolas nicolas 1290 août   3 08:42 45878_tapisserie_01
-rw-r--r-- 1 nicolas nicolas  574 août   3 08:42 48778_tapisserie_02
-rw-r--r-- 1 nicolas nicolas  574 août   3 08:42 54124_tapisserie_10
-rw-r--r-- 1 nicolas nicolas 1212 août   3 08:42 60934_tapisserie_05
-rw-r--r-- 1 nicolas nicolas 3877 août   3 08:42 61772_tapisserie_03
-rw-r--r-- 1 nicolas nicolas   94 août   3 08:41 etendard_1
-rw-r--r-- 1 nicolas nicolas   93 août   3 08:41 etendard_2
-rw-r--r-- 1 nicolas nicolas   94 août   3 08:41 etendard_3
-rw-r--r-- 1 nicolas nicolas   94 août   3 08:41 etendard_4
-rw-r--r-- 1 nicolas nicolas   47 août   2 18:46 piece_1
-rw-r--r-- 1 nicolas nicolas   47 août   2 18:46 piece_2
-rw-r--r-- 1 nicolas nicolas   47 août   2 18:46 piece_3

~
[mission 12] $ 
`

**Comment by phyver** [comment]
Si la mission échoue, le tableau est supprimé du coffre et la mission est réinitialisée avec de nouveaux tableaux. Il faut donc recommencer la mission en entier.
C'est le comportement attendu.
Est-ce que c'est ce qui se passe ?

**Comment by lescobales** [comment]
Lors du `gsh check` le tableau est supprimé alors que je mets le tableau le plus ancien dans le Coffre. Si je fais un `chmod 500` sur le tableau et si celui ci est le plus ancien, cela fonctionne. Si je fais `chmod 500` sur un tableau qui n'est pas le plus ancien le retour est que le tableau n'est pas dans le coffre.

**Comment by phyver** [comment]
Est-ce que la mission réussit ?
Si non, tu n'as probablement pas le tableau le plus vieux.

Attention, pour retrouver le tableau le plus vieux, il faut bien regarder l'année dans le résultat de `ls -l`. Si tu regardes juste le jours et mois, tu risque de ne pas trouver le bon tableaux. (Le tableau le plus vieux doit avoir une date entre 1980 et 1990.)

**Comment by lescobales** [comment]
Effectivement, c'est une erreur de ma part. Je m'excuse pour le dérangement. En tout cas, merci pour ce jeu qui est très bien réalisé.

**Comment by phyver** [comment]
Merci !
