### ISSUE TITLE
Error resolving mission 41

### ISSUE THREAD

**Issue by Adjenz** [phyver/GameShell#110]
Hey Pierre, 

I have another issue, this time with the mission 41. When I `gsh check` it doesn't let me enter the number of dettes, it automatically says "Wrong answer" then I have this error message : 

`sh: 0: getcwd() failed: No such file or directory`

**Comment by phyver** [comment]
Oops, that was a bug.
It should be fixed by 99594301.

**Comment by Adjenz** [comment]
Thanks !
By the way I really loved the homeopathic recipe !
