### ISSUE TITLE
Mission 29

### ISSUE THREAD

**Issue by lescobales** [phyver/GameShell#112]
Bonjour,
Lors du `check goal` l'instruction dit de ne pas tuer le lutin. Nous avons essayé avec mon fils d'utiliser kill -6 sur les processus correspondant aux sortilèges du Lutin. Le retour de `gsh check` a été "Est ce que vous avez tué le Lutin". Ensuite nous avons de nouveau procédé de la même manière et en tuant le lutin et nous avons toujours le même retour.....Nous aimerions avoir un indice pour résoudre cette mission.
Merci

**Comment by phyver** [comment]
Ce n'est pas normal!
Ré-essayez, et lancez la commande
`````
  $ pstree -p $$
`````
juste avant de faire le `gsh check`.

Normalement, le processus du lutin est encore là, mais vous avez dû tuer ses sortilèges.

Remarque, pour cette mission, il n'est pas nécessaire de spécifier du numéro de signal à envoyer. Par défaut, `kill` envoie le signal 15 (`SIGTERM`), ce qui doit arrêter le processus.

**Comment by phyver** [comment]
Je ferme ce rapport de bug. N'hésitez pas à le réouvrir si besoin.
