### ISSUE TITLE
mission 18 chromeos

### ISSUE THREAD

**Issue by Fred73140** [phyver/GameShell#113]
i play gameshell on my chromebook, when i open the terminal xeyes works but when i play gameshell (mission 18), xeyes won't open

no protocol specified
error: can't open display: :0

anybody have a solution?

**Comment by phyver** [comment]
I've never used ChromeOS, but that's a little strange.

Can you give me the value of the `DISPLAY` variable (output of `echo $DISPLAY`)
  - from a plain terminal (that can run `xeyes`)
  - from a terminal (that cannot run `xeyes`)

**Comment by Fred73140** [comment]
on the terminal i obtain :0
and when i launch gameshell, i have the same value :0

**Comment by phyver** [comment]
Mmm...
Then, I don't know what is happening, and since I don't have access to a chromebook, I'm not sure this will be fixed anytime soon.

For the time being, you can skip this mission by running `gsh skip` from within GameShell. (The default password is `gsh`.)

**Comment by phyver** [comment]
The error message is different, but this could be related to #116.

Can you give me the output of
``````
    $ xauth list
    $ echo $XAUTHORITY
``````
from a "normal" terminal **and** from a terminal running GameShell?

**Comment by Fred73140** [comment]
je viens de m'apercevoir que vous êtes de Chambéry, je travaille aussi à Chambéry.
la solution au problème est celle aue vous mentionnez dans ce post:
https://github.com/phyver/GameShell/issues/116#issuecomment-1207233832

Merci de votre aide. 
Et encore bravo pour ce jeu j'adore

**Comment by phyver** [comment]
Merci à toi !
