### ISSUE TITLE
Lancement sur Raspberry Pi

### ISSUE THREAD

**Issue by xaviergregor** [phyver/GameShell#12]
Bonjour, 
Sur un Raspberry Pi avec Raspbian installé j'obtiens cette erreur au lacement du jeu : 

`la variable 20104OSTYPE est égale à linux-gnueabihf
je ne reconnais pas ce système...`

**Comment by phyver** [comment]
Ah...
Je n'ai pas de Raspberry sous la main, mais le probème vient peut-être de la mission 30, qui compile un petit programme en C lors de la génération de la mission.

Tu peux essayer de lancer la commande  `gcc -o merlin merlin.c` depuis le répertoire `GameShell/missions/30_stdout_stderr_redirection`, dans un shell standard ?

**Comment by xaviergregor** [comment]
Je viens de le faire et toujours la même erreur lors du lancement
Je vais testé sur une autre distribution (Debian ?) 
Merci

**Comment by phyver** [comment]
Lance la commande `gcc -o merlin merlin.c` dans ton shell standard, sans essayer de démarrer GameShell.
Cette commande est lancée par GameShell pour générer une mission, et je voudrais voir si c'est elle qui cause l'erreur.

**Comment by xaviergregor** [comment]
Oui je l'ai lancée dans GameShell/missions/30_stdout_stderr_redirection elle s'execute sans problème

**Comment by phyver** [comment]
Ça devrait fonctionner grace à la correction de DaakMoon.
Tu peux confirmer ?

**Comment by xaviergregor** [comment]
Super ça fonctionne merci DaarkMoon
