### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Williamrjw** [phyver/GameShell#125]
Without DISPLAY in mission 18!
no ENV tag in the dockerfile!
BTW, what's mission 18 goal and commands?

**Comment by Williamrjw** [comment]
Noticed. I just ignored the manual.
And how many missions with DISPLAY?
Or how can I restart the game without the 17 missions before?

**Comment by phyver** [comment]
Sorry for the delay...

Mission 18 is the only one that requires an X-server.

You can skip missions with the `gsh skip` command. If you're using the version from the official repository, the password is simply `gsh`.
(There is also a `gsh goto N` mission that allows to go directly to any mission you want. You can get the list of missions with their number with `gsh index`.)
