### ISSUE TITLE
/missions/stdin_stdout_stderr/04_stderr_dev-null_grimoires/ goal

### ISSUE THREAD

**Issue by Pada0** [phyver/GameShell#127]
In my opinion the goal in this mission, both in EN or FR version, is not enough accurate. We don't understand that we have to print the list in stdout (or display) and redirect stderr to dev/null and not write it to a file like in the previous mission.
Also we can maybe change COMMAND > FILE by COMMAND 1> FILE like COMMAND 2> FILE
This mission is a big step in the progression.

**Comment by Mte90** [comment]
Can you propose a better goal in text form?

**Comment by Pada0** [comment]
Actually not. But the "2>" for stderr is hard to catch
