### ISSUE TITLE
Mission 28 and 29 (Mac OS): Some dependencies are not met

### ISSUE THREAD

**Issue by COValhalla** [phyver/GameShell#129]
I'm on Mac OS and when I reached Mission 28, it skipped as well as skipping Mission 29. The errors are shown below:

[mission 30] $ gsh goto 28
compilation failed
Process names should be equal to the corresponding filename for mission processes/02_ps_kill_signal/deps.sh.
Error: mission 28 is cancelled because some dependencies are not met.
Process names should be equal to the corresponding filename for mission processes/03_pstree_kill/deps.sh.
Error: mission 29 is cancelled because some dependencies are not met.

I'm not really sure about to go about debugging this one. I'll see if I can dive into it later. ps and pstree already work in Mac with no issues so I'm not sure what the dependency issue is here.

**Comment by phyver** [comment]
Do you have a C compiler (clang or gcc) installed?
That is necessary for mission 28 and 29.
