### ISSUE TITLE
Missing some hint at the beginning?

### ISSUE THREAD

**Issue by gponzo** [phyver/GameShell#134]
I've being playing with my little daughter and in the very first mission she chose a wrong directory.

The fact is that the first hints report just "cd", "ls" and "pwd" commands, which could be enough, but there isn't (yet?) the "cd .." hint to know how to go back (and choose a different directory).

**Comment by rlepigre** [comment]
Indeed not, but you can always do `gsh reset` (see `gsh help`) to restart the current mission from the beginning.

**Comment by phyver** [comment]
Indeed.
That's probably the easiest; and both `gsh check`, `gsh reset` should take you back to `$HOME`, while both `gsh help` and `gsh goal` will tell you about `gsh reset`.
