### ISSUE TITLE
Duplicate dirnames (lower/upper case) in subdir i18n

### ISSUE THREAD

**Issue by thomasmerz** [phyver/GameShell#145]
In subdir [i18n](https://github.com/phyver/GameShell/tree/master/i18n) there are the same dirnames both in lower and in upper case:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'i18n/gameshell-HELP/en.txt'
  'i18n/gameshell-help/en.txt'
  'i18n/gameshell-HELP/fr.txt'
  'i18n/gameshell-help/fr.txt'
  'i18n/gameshell-HELP/it.txt'
  'i18n/gameshell-help/it.txt'
  'scripts/_gsh_HELP'
  'scripts/_gsh_help'
```
I think @phyver introduced these duplicates with commit https://github.com/phyver/GameShell/commit/d366dff1779a3c4d24c43c3ff3d30f34469288c7

Please check out my upcoming PR for deduplication…

**Comment by phyver** [comment]
Ah! Those still exist!
I rejected your PR because I want to have the 2 commands `help` and `HELP` to display different things.
(simple help message or full help message)

I just pushed a commit 82bd7043  that should correct that. Can you try and confirm it works on your system.

**Comment by thomasmerz** [comment]
This works on my insensitive filesystem (APFS on MacOS which could also be sensitive, but due to a mistake "someone" chose the wrong/suboptimal format 😞). Thanks a lot!

**Comment by phyver** [comment]
Thanks for the bug report and testing!
