### ISSUE TITLE
Italian translation for missions 19 and 20

### ISSUE THREAD

**Issue by phyver** [phyver/GameShell#147]
@Mte90
I just pushed 2 new missions on master (e0ff64cd): missions 19 and 20 (`intermediate/05_background` and `intermediate/06_control-C`).

It would be great if you can translate them. (files `goal/it.txt` and `i18n/it.po`).
I haven't tested it but it should fall back to English at the moment...

**Comment by Mte90** [comment]
I will do it in the next few days!

**Comment by phyver** [comment]
merged in ce693a8 and b4ab210
