### ISSUE TITLE
Mission 19 bug

### ISSUE THREAD

**Issue by PoloNose** [phyver/GameShell#151]
There seems to be a problem in mission 19 (where the artificer asks the player to shoot fireworks using the charmiglio command) as whatever I do I always end up with the message "hum, I can't see anything". I tried looking at the code used to check the success of the mission but I fear there's good reason I was advised to play this game. I can only suppose it has to do with the way the gale checks the number of fireworks that were actually shot. If it helps, I'm playing the game in French, maybe it has to do with the fact the text in the check.txt file is in English? It also seems like a file used to store the number of fireworks shot is deleted before the data it stored was used.
Thanks in advance for any help, as I'd love to finish this minigame.

**Comment by phyver** [comment]
Sorry about that.
This mission rather new and hasn't been tested "in the field" with students, yet.
You're not the first to have problems with it.
An upcoming commit will add a hopefully helping message when the `check` command fails: `NOTE: you need to make sure the pyrotechnician sees all the fireworks while he is waiting.`
(Or, in French: `NOTE : vous devez vous débrouiller pour que l'artificier voie tous les feux d'artifice pendant qu'il attend.`)

Does that help?

(If not, I might have to rethink the whole thing...)


Note also that it is always possible to skip a mission and go to the next one with the `gsh skip` command. The default password is simply `gsh`.
(If you're using that in a classroom, the teacher has hopefully changed it to something else though...)

**Comment by phyver** [comment]
The above message is now on master.
Don't hesitate to reopen the issue if that doesn't answer your question.
