### ISSUE TITLE
compte à rebours sur Mission 35

### ISSUE THREAD

**Issue by fanfu** [phyver/GameShell#18]
En commençant la mission 35, le compte à rebours du nombre de commandes de la mission 34 continuait. Je n'arrivais pas à valider la mission. En quittant le jeu et en revenant, il n'y avait plus de compte à rebours. La même requête a permis de passer le niveau.

**Comment by phyver** [comment]
Est-ce que tu es sûr que tu ne pouvais pas valider la mission suivante ?

Tu avais probablement utilisé une redirection `... | gash check`. Il y avait effectivement un bug qui ne remettait pas la variable `$PROMPT_COMMAND` à jours, et l'affichage restait pour les missions suivantes.
Par contre, ça ne devrait pas influencer les `gash check` des missions suivantes.

Le bug est normalement corrigé, même si ce n'est pas entièrement satisfaisant. (cf message du commit pour les détails)
