### ISSUE TITLE
Mission 17: xeyes 

### ISSUE THREAD

**Issue by plasmasyl** [phyver/GameShell#19]
Bonsoir,
merci pour cette idée de jeu pour l'apprentissage des commandes élémentaires Shell: c'est absolument génial.
Personnellement, je rencontre une difficulté avec la mission 17 xeyes ne se lance pas au travers de l'application. J'obtiens l'erreur suivante :
`[mission 17] $ xeyes 
Error: Can't open display:`

Dans le terminal simple, l'appli xeyes fonctionne. Comment est-il possible de contourner ce problème qui semble plus être lié à mon système qu'au programme lui-même? Je suis sous Opensuse Leap 15.2.

Merci beaucoup pour votre aide et éventuelle correction.

**Comment by phyver** [comment]
Étrange.
Tu peux faire l'expérience suivante dans un terminal et de donner les résultats ?
```
$ echo $DISPLAY
$ bash
$ echo $DISPLAY
$ exit
$ bash GameShell/start.sh
...
[mission 01] $ echo $DISPLAY
```

**Comment by phyver** [comment]
Ah...
Tu n'utilise probablement pas la dernière version.
DaarkMoon a normalement corrigé ce bug il y a quelques jours.

**Comment by phyver** [comment]
Ah...
Tu n'utilise probablement pas la dernière version.
DaarkMoon a normalement corrigé ce bug il y a quelques jours.

**Comment by phyver** [comment]
N'hésite pas à réouvrir le bug si ça n'est pas corrigé.

**Comment by plasmasyl** [comment]
C'est parfait, tout fonctionne correctement avec la dernière version.
Merci beaucoup!
