### ISSUE TITLE
(macOS) Erreur après la mission 10 

### ISSUE THREAD

**Issue by iFredOS** [phyver/GameShell#2]
Jusqu'à cette mission il y a avait aucun problème. Voici ce que ça écrit après un `gash check` pour la mission 10 :

```
La mission 10 est validée

stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
****************************************
*  Tapez la commande                   *
*    $ gash show                       *
*  pour découvrir l'objectif suivant.  *
****************************************
```

**Comment by rlepigre** [comment]
L'erreur est liée au `init.sh` de la mission 11, pas de rapport avec la mission 10. D'ailleurs, l'origine du problème est la même que pour #3: il faut utiliser `gstat` de `coreutils` au lieu de `stat`, de la même manière qu'il faut utiliser `greadlink` au lieu de `readlink`.

D'après ce que j'ai compris, macOS utilise les variantes BSD des commandes, alors que Linux utilise les versions GNU (fournies par `coreutils`).

**Comment by iFredOS** [comment]
Je pense que c'est exactement ça. Je joue au sur Debian sans problème mais sous macOS, il y a une certaine adaptation à faire.

**Comment by phyver** [comment]
Je viens de faire quelques patch pour utiliser ``gstat`` au lieu de ``stat``.
Est-ce que ça marche ?
