### ISSUE TITLE
`pstree` is not a dependency for mission `03_pstree_kill `

### ISSUE THREAD

**Issue by phyver** [phyver/GameShell#45]
The presence of `pstree` is not checked in `processes/03_pstree_kill/init.sh`, and the goal file does say the command is not standard.
We can either
  - add `pstree` has a real dependency and cancel the mission if it is not found,
  - or talk about `PPID` and `ps -f` (that should make it possible to finish the mission)

@rlepigre , what do you think?

(Maybe we can have a real dependency for `pstree`, and have some other mission use `PPID`...)

**Comment by rlepigre** [comment]
Yeah, maybe we can make it a dependency for now, and we can always add another of the version later.
In general I think it is good to have more options: we don't need to include all the missions in the default index file.

**Comment by phyver** [comment]
a534684ae83a5db65fe0edb8b1289628d884fc92
