### ISSUE TITLE
(macOS) Ne retient pas la progression du jeu.

### ISSUE THREAD

**Issue by iFredOS** [phyver/GameShell#5]
Après avoir fait exit et j'ai tenté de retourner dans le jeu pour continuer où j'avais laissé mais ça recommence à la « mission 01 ».

```
$ ./start.sh 
Attention, vous êtes en train d'exécuter
GameShell dans la version de développement.
Faut-il le continuer ? [o/N] o
'/Users/ifredos/Documents/GitHub/GameShell/.session_data' existe déjà... Faut-il le conserver ? [O/n] O

~
[mission 01] $ 
```

**Comment by phyver** [comment]
J'imagine (j'espère) que c'est le même bug que celui lié à la sauvegarde sous macOS.

Est-ce que tu peux ré-essayer ?

**Comment by iFredOS** [comment]
Est-ce que ça se peut qu'à cause que c'est en version développement que je ne puisse pas continuer où j'étais rendu? Je me suis juste rendu à la mission 02 et ça me ramène toujours à la première mission.

```
$ ./start.sh
Attention, vous êtes en train d'exécuter
GameShell dans la version de développement.
Faut-il le continuer ? [o/N] o
'/Users/ifredos/GameShell/.session_data' existe déjà... Faut-il le conserver ? [O/n] O
[mission 01] $
```
