### ISSUE TITLE
`gsh exit` is not exiting

### ISSUE THREAD

**Issue by duthils** [phyver/GameShell#56]
# Scenario

Given I start the game and start `mission 1`
When I type `gsh exit`
Then I see the prompt `[mission 1] $`

Expected: Then the game exits

Note: CTRL-D exits the game correctly.

Here is the list of the commands entered:

```
bash gameshell.sh
[mission 1] $ gsh exit
[mission 1] $
```

# Environment

* Archlinux
* GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)

**Comment by phyver** [comment]
Thanks!
That was fixed on the `zsh` branch, but for now, c569cd0f should fix it.
