### ISSUE TITLE
`gsh reset` error `getcwd: cannot access parent directories`

### ISSUE THREAD

**Issue by duthils** [phyver/GameShell#57]
# Scenario

Given I start mission 4
Given I create a Hut inside the Forest
Given I go to the Hut
Given I create a Chest inside the Hut
When I enter `gsh reset`
Then I see errors:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory                                                                                                 
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
...
```

Expected: mission 4 is reset

Here is the list of commands:

```
cd Forest/
mkdir Hut
cd Hut
mkdir Chest
gsh reset
```

# Environment
* Archlinux
* GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)

**Comment by phyver** [comment]
Good catch. The `gsh reset` was removing the Hut / Chest you had created.

b2fec226 should fix this.

I now check `$PWD` doesn't contain the Hut / Chest. If it does, I `cd ~` before removing the Hut / Chest.
