### ISSUE TITLE
Le message d'introduction ne s'affiche pas avant la mission 1

### ISSUE THREAD

**Issue by clavierp** [phyver/GameShell#6]
Au lancement de la première mission, le message d'accueil ne s'affiche pas.
Visiblement, le problème vient du `lib/bashrc` ligne 24, le message ne s'affiche que si on est pas en GASH_DEBUG_MISSION.

**Comment by phyver** [comment]
corrigé !
gash se lançait automatiquement en mode DEBUG sur la mission 1 lorsqu'on l'exécutait depuis le dossier de developpement.
C'était probablement une mauvaise idée...
