### ISSUE TITLE
Error on the verification of the use of the head command

### ISSUE THREAD

**Issue by HdG-0** [phyver/GameShell#60]
I just discovered GameShell (and I think it's really great!) but I'm stuck at mission 22 because I don't use the head command even though I use it.

Details :
- Mission : 22 
- Objective : Display the recipe of the herbal tea
- Error : Unable to validate the mission despite using the command
- OS : Fedora
- Screenshot : 
![gameshell](https://user-images.githubusercontent.com/87321009/125307884-fa6ef880-e31f-11eb-8095-437b419ad67d.png)

Thanks for your work on this really cool project :)

**Comment by phyver** [comment]
Thanks!

Can you give me the output of `gsh systemconfig`?

Also, try running the following command
```
[mission 22] sed -i '5s/$/\necho ">>> FC -LNR";. fc-lnr.sh; echo "<<<DONE";/' "$GSH_MISSIONS/pipe_intro_book_of_potions/01_head/check.sh"
```
and then trying to complete the mission.

`gsh check` should output something of the form
```
>>> FC -LNR
...
...
<<<DONE
```
There should be the commands you've run, in reverse order. Can you give me
  - the list of commands you've run
  - the output of `gsh check`?

**Comment by phyver** [comment]
Ah!
I think I know what happens. That's because of the alias `gc=`gsh check`.
I'll try fixing it.

In the meanitme, don't use your alias to check the missions with Servillus. :(

**Comment by phyver** [comment]
Can you confirm the last commit (a98e4ea2) fixes the problem?

**Comment by HdG-0** [comment]
It is good! Everything works! 
Thank you and sorry for the delay :)

**Comment by oupala** [comment]
In fact, the issue that I am mentionning for missions 22 and 23 are not due to a modified file in the book of potion. It is only due to being into the book of potion instead of being just in the cave.

I changed my messages above so it is easier to reproduce the issue (that I'm reproducing with the last Dockerfile from GitHub).
