### ISSUE TITLE
cleaning the `Book_of_potions` directory

### ISSUE THREAD

**Issue by phyver** [phyver/GameShell#64]
If the user creates spurious files in `Book_of_potions`, they are not removed when the mission is reset.

**Comment by oupala** [comment]
In fact, I don't see why both cases should be error.

- If the user is adding some files to the book (like adding a new receipe), it should not be a problem.
- If the user is diving into the "book of potions" directory, why should it be a problem?

As long as the mission goal is reached, the mission should be a success:

> [mission 22] $ cd World/Mountain/Cave/Book_of_potions

**Comment by oupala** [comment]
Currently, the script does not detect if I'm inside the book of potion.

It is however detecting that I altered the book of potion. But nothing told me not to alter the book of potion. If it is really forbidden to alter the book of potion, the book of potion should be read-only.
