### ISSUE TITLE
Comment choisir la langue ?

### ISSUE THREAD

**Issue by Cantor42** [phyver/GameShell#65]
Peut-être plus une incompréhension de ma part qu'une issue. J'utilise GameShell avec mes lycéens, le jeu se lance automatiquement en français sur les ordinateurs (Ubuntu 20.04) de ma salle. En revanche, j'ai testé avec Cygwin et malgré un `export LC_ALL=fr_FR.UTF-8` le jeu se lance en anglais. Comment faire ?

**Comment by phyver** [comment]
Je n'y crois pas trop, mais tu peux essayer de lancer GameShell avec
```
$ gameshell -L fr
```


Sinon,
```
$ export LC_MESSAGES=fr_FR.UTF-8
```
avant de lancer GameShell a plus de chance de fonctionner, à condition que la locale soit effectivement installée.


Est-ce que tu peux me donner le résultat des commandes
```
$ locale
```
et
```
$ locale -a | grep FR
```
sur la machine Cygwin ?

**Comment by Cantor42** [comment]
La première suggestion ne fonctionne pas, gameshell n'étant pas une commande.  Je le lance avec `$ bash gameshell.sh`, le `-L fr` n'a pas résolu le problème. Quant à la deuxième solution, j'ai tapé ceci avant de lancer et cela n'a rien résolu.

```
Bob@Antec ~
$ locale
LANG=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=

Bob@Antec ~
$ export LC_MESSAGES=fr_FR.UTF-8

Bob@Antec ~
$ locale
LANG=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_ALL=

Bob@Antec ~
$ locale -a | grep FR
br_FR
br_FR.utf8
br_FR@euro
co_FR
co_FR.utf8
co_FR@euro
fr_FR
fr_FR.utf8
fr_FR@euro
gsw_FR
gsw_FR.utf8
gsw_FR@euro
oc_FR
oc_FR.utf8
oc_FR@euro
```

**Comment by phyver** [comment]
Ta locale par défaut est `C.UTF-8`, qui donne des messages en anglais.

Je suis un peu surpris que `LC_MESSAGES=fr_FR.UTF-8` ne fonctionne pas, mais je ne sais pas comment Cygwin gère les noms de locales.

Est-ce que tu peux essayer avec
```
$ export LC_MESSAGES=fr_FR.utf8
$ bash gameshell.sh
```
?
