### ISSUE TITLE
Un seule pièce d'or générée dans la mission 20

### ISSUE THREAD

**Issue by clavierp** [phyver/GameShell#7]
Une seule pièce d'or est générée dans la mission 20
`⌁ [paul:~/GameShell/World] master(+1/-2)* 2m46s ± find . | grep or
./Chateau/Cave/.Long 479b2e2d850d39004736f4bab8ef5e46fe2c2939 Couloir 23996d45c6454f970f0aa3e13661309a806ddcd2/labyrinthe/c3a74cd00b012f0c533ecbedd4d398090e104214/fa9595baa5566befb5df584c2469f1a043aadcfc/a53f8154a05b40b5279eeb76e0a991f8ab4f673b/piece_d_or
./Chateau/Entree/b3324084269b866d11ac523f4496a4ed10bf7551_ornement
./Chateau/Entree/3ca08c59b85ddf86c208f5c7f710ef998d79eca9_ornement
./Chateau/Entree/8674f7c63466d2d1ad6a57c9a4721bf6c11f07cf_ornement
./Chateau/Entree/73f4417a15ef2df55edaf818d7925e90e5329999_ornement
./Chateau/Entree/261d28f9e14d18ddbf7757ffa7fafec5db85bd60_ornement
./Chateau/Entree/5d16725337efe6610230da3dda25e1ffedb24409_ornement
./Chateau/Entree/278396974ca068fca1a63ed2618a46428893cd03_ornement
./Chateau/Entree/aef5d4749fcb89c87dbd412b0a3d1efc028b9ff2_ornement
./Chateau/Entree/8e1fb61a973ff350a16ebebd6aa4020bb52a5984_ornement
./Chateau/Entree/07a235cc6046149cdd0464898fde061c7216e2fd_ornement
./Foret
./Foret/Cabane
./Foret/Cabane/b3324084269b866d11ac523f4496a4ed10bf7551_ornement
./Foret/Cabane/3ca08c59b85ddf86c208f5c7f710ef998d79eca9_ornement
./Foret/Cabane/etendard_3
./Foret/Cabane/8674f7c63466d2d1ad6a57c9a4721bf6c11f07cf_ornement
./Foret/Cabane/73f4417a15ef2df55edaf818d7925e90e5329999_ornement
./Foret/Cabane/261d28f9e14d18ddbf7757ffa7fafec5db85bd60_ornement
./Foret/Cabane/5d16725337efe6610230da3dda25e1ffedb24409_ornement
./Foret/Cabane/etendard_4
./Foret/Cabane/278396974ca068fca1a63ed2618a46428893cd03_ornement
./Foret/Cabane/aef5d4749fcb89c87dbd412b0a3d1efc028b9ff2_ornement
./Foret/Cabane/etendard_2
./Foret/Cabane/Coffre
./Foret/Cabane/Coffre/piece_de_bronze
./Foret/Cabane/Coffre/.piece_eec222fed93066c280925ad209046bee157a7da2_1
./Foret/Cabane/Coffre/.piece_cb00d12be357e95be59ec2a1481d9107bd83b3f5_3
./Foret/Cabane/Coffre/piece_3
./Foret/Cabane/Coffre/tableau
./Foret/Cabane/Coffre/.piece_5e4949f59059bc35731958865bc215731723a200_2
./Foret/Cabane/Coffre/piece_1
./Foret/Cabane/Coffre/piece_2
./Foret/Cabane/8e1fb61a973ff350a16ebebd6aa4020bb52a5984_ornement
./Foret/Cabane/etendard_1
./Foret/Cabane/07a235cc6046149cdd0464898fde061c7216e2fd_ornement
`

**Comment by phyver** [comment]
Indice : en plus d'une `piece_d_or`, il peut également y avoir une `piece_d_Or`...

**Comment by clavierp** [comment]
effectivement, ça m'apprendra à utiliser iname
