### ISSUE TITLE
WISH: Add a few examples to the README

### ISSUE THREAD

**Issue by HenrikBengtsson** [phyver/GameShell#74]
Hi, thanks for developing this.

For someone "shopping around", it's hard to get an idea what this software actually does and what the "student" will experience, without installing and running it.

I'd like to suggest updating the README.md with a few, simple, static examples that show what the input and output of the game look like.

**Comment by rlepigre** [comment]
That is a good point! We actually considered (and I tried) creating an animated GIF that demonstrates what the start of the game looks like, but it was not as easy to do as I thought. Maybe we should give this another shot?

**Comment by HenrikBengtsson** [comment]
Those GIFs can be tedious to create and maintain. Plain text, static, examples have the advantage of being accessible.

**Comment by phyver** [comment]
We should definitely do something about that!

**Comment by phyver** [comment]
Just tried generating a gif for the first mission:  https://github.com/phyver/GameShell/tree/tmp

What do you think?

**Comment by phyver** [comment]
And I added some a plaintext overview of the first mission later in the README.md file as well.

If you think that's good, I can add the same thing to the French README file!

**Comment by rlepigre** [comment]
I like the GIF! And the plaintext overview cannot hurt, so I'd keep both.

**Comment by HenrikBengtsson** [comment]
LGTM.  Yes, plain-text overview will be nice, especially from an accessibility perspective.
