### ISSUE TITLE
Merlin s'est fait écraser

### ISSUE THREAD

**Issue by clavierp** [phyver/GameShell#8]
J'ai écrasé Merlin par erreur dans la mission 30. Un `gash restart` ne le fait pas réapparaître, une suppression suivie d'un restart non plus.

**Comment by clavierp** [comment]
idée: déplacer l'appel à gcc de static.sh à init.sh?

**Comment by clavierp** [comment]
ça marche chez moi, il me reste plus qu'à trouver comment faire une pull request.

**Comment by AbbouElectronics** [comment]
Bonjour Monsieur

je suis étudiant à l'université de bab ezzouar (USTHB) À ALGER Master 1
 electronique des systèmes embarqués,J'ai besoin de la solution de
Tp5:mini projet,gérer une "TODO list".
S'il vous plaît

cordialement.

**Comment by phyver** [comment]
C'est corrigé. `init.sh` appelle `gcc`, et Merlin est regénéré à chaque fois.
