### ISSUE TITLE
How to localize it

### ISSUE THREAD

**Issue by Mte90** [phyver/GameShell#81]
I see that for every mission there are languages files.

There is a guide about it (the readme doesn't mention anything)? I will be interested in localize it in italian.

**Comment by Mte90** [comment]
nenvermind I found it... https://github.com/phyver/GameShell/blob/master/doc/i18n.md

**Comment by phyver** [comment]
That would be great!
Don't hesitate to ask if you need more info.

You can open an issue "Italian translation" so you can tell us about any progress you make.
