### ISSUE TITLE
Un mot de passe admin un poil plus solide

### ISSUE THREAD

**Issue by clavierp** [phyver/GameShell#9]
J'étais en train de me balader dans les sources et j'ai trouvé le hash du mot de passe (c'est bien!), mais google le connaît aussi (c'est moins bien).
Ça m'a donné faim d’ailleurs.

**Comment by phyver** [comment]
Oups, j'avais jamais répondu...

La commande `bin/archive.sh` permet de générer une archive de GameShell avec un autre mot de passe que celui par défaut. (option `-P`)
