### ISSUE TITLE
Is this part of a previous stage of the game?

### ISSUE THREAD

**Issue by Aierbote** [phyver/GameShell#91]
I was wondering what this thing meant
>       | gsh exit                                            |.
>       |   quit GameShell                                    |.
>       |   (you can start from the current mission by        |.
>       |   running the start.sh script with the "-C" flag)   |.

cause I see no `start.sh` in the folder when I `git cloned` the game.

So, ask said in the title: **Is this part of a previous stage of the game?**

I've even tried to run `man gameshell.sh` and `man gsh` but there is none

**Comment by rlepigre** [comment]
That indeed seems outdated: when you quit the game, a script `gameshell-save.sh` is created that you can run to resume the session where you left it the last time.

**Comment by phyver** [comment]
fixed by 48e7592f
