### ISSUE TITLE
[suggestion] - Additional missions ideas

### ISSUE THREAD

**Issue by Aierbote** [phyver/GameShell#97]
First thing first, I have finished _all_ the mission _(except skipped ones)_ . It was a wonderful experience, and I'm glad this way I learnt something new in a fun way

After completing the game I realized I could be reading from time to time my `journal.txt` and decided to generate a hard link it and it worked. While I loaded my `gameshell-save.sh` in another terminal window I ran `$ sudo ln gameshell/World/Forest/Hut/Chest/journal.txt`

And this gave the idea that there should be a couple of missions about creating **hard link** and a **symlink** (aka **soft link**) and to get the differences between those two with all pros and cons (for example I just read about _dangling soft link_ and the trouble of recreating a file with the same name of the previous soft linked file). So maybe mentioning inodes too.

-----

It would be nice to have more examples of useful <kbd>ctrl</kbd> hotkeys in terminal (discovering `^L` was fantastic, especially in _that mission..._ it saved my sanity) and for now I can just think of `^R` and `^Z` (couldn't it be an alternative to the mission of background command `COMMAND &` that was skipped?)

**Comment by phyver** [comment]
Glad you liked it!

Having missions about symbolic links has been in my TODO list for a long time: making shortcuts, portals or secret passages would fit right in GameShell!

I'm not so sure about hardlinks. They're not available on all filesystems, and to tell the truth, I don't find them very useful. (I've only really used them a couple of times, indirectly with `cp -al`, or when explaining them to students!)

There are several other ideas in the file `doc/mission_ideas.md`.
